.TH EMACS-LUCID 1 "2026-06-29" "GNU Emacs" "Fedora Linux"
.
.SH NAME
emacs-lucid \- Emacs with support for X11, using the Lucid toolkit
.
.SH SYNOPSIS
.B emacs-lucid
[
.I command-line switches
] [
.I files ...\&
]
.
.SH DESCRIPTION
Fedora Linux includes several different builds of GNU Emacs, each using
different graphical toolkits (or none at all).
.
.P
The \fBemacs-lucid\fR binary uses the Lucid toolkit, for use on the X
Window System.
.
.P
Note that a favoured build can be selected using the \fBalternatives\fR
system.
.
.SH SEE ALSO
.BR alternatives (8),
.BR emacs (1),
.BR emacs-desktop (1),
.BR emacs-gtk+x11 (1),
.BR emacs-nw (1),
.BR emacs-pgtk (1),
.
.SH AUTHORS
Peter Oliver
.
.\" Local Variables:
.\" eval: (add-hook 'before-save-hook 'time-stamp nil t)
.\" time-stamp-pattern: "^\\.TH [^ ]+ [^ ]+ \"?%Y-%m-%d\\_>"
.\" time-stamp-time-zone: "UTC0"
.\" End:
